### PR TITLE
Changed hotkeys to bind and unbind on focus

### LINKED ISSUE #49: The app blocks Ctrl-R hotkey
When app is running Ctrl-R hotkey doesn't work system-wide. Browsers, terminal, etc.
Linux Mint 19.3 Cinnamon

### LINKED ISSUE #58: Dev keys grabbed/registered in Production build
Hey there,

I'm on Windows using WSL and it took me a while to figure out why I can't use CTRL-R in bash anymore. The culprit seems to be productivity timer (found out via VS tool spyxx).

I suspect the function `registerGlobalShortcut` (https://github.com/roldanjrCodeArts9711/productivity-timer/blob/dc00c43dab3b72ce3295bd995b1318978c23bdd7/app/public/electron.js#L81) and propose to construct the `shortcutKeys` array in a different way: merge production with dev for dev builds. Right now it seems to grab keys unnecessarily with empty callbacks.

Hope you can fix and re-release soon, would love to use the app afterwards again.
Cheers!

### PR DESCRIPTION
**Pull request by sekwah41**
This change is to resolve #58 and resolve #49

### CODE REVIEW

**Comment by roldanjrCodeArts9711** [comment]
@sekwah41 Thanks for helping. 👍

**Comment by jedsonmelo** [comment]
@sekwah41 the shortkeys not working when the app is closed and stay running in background :disappointed:

**Comment by sekwah41** [comment]
@jedsonmelo i would recommend minimising it rather than closing it for now as that works. I can make a pr later to also fix this.

**Comment by sekwah41** [comment]
I have made a new pull request fixing this @jedsonmelo as #61

**Pull request merged**
